##### This file can be used for Installing Only Argo Rollouts ###############################
##################################################
argo-rollouts:
  # Default set to true . Set to false if crds already exists in the cluster instead of deleting the CRDs
  installCRDs: true
####################################################

global:
  argorollouts:
    host: "ROLLOUTS.REPLACE.THIS.WITH.YOURCOMPANY.COM"

  #####User doesn't need to change the below flags let it be the default one######################
  minio:
    enabled: false

  ###############################################################################
  # Set it to false if own LDAP is to be configured
  installOpenLdap: false

  ## ldap configuration used for authentication and authorization
  ldap:
    enabled: false

#######################################################################################################################
## Redis configuration
installRedis: false
####################################################
# installArgoCD enable true will install argo-cd,argo-rollouts,argo-workflows,argo-events,argocd-image-updater
installArgoCD: false
###########################################################################################
#  OEA-AP Install OEA and Argo Services . Change to None if only Argo Services to be installed.
installationMode: None

# installkeycloak enable true if user need to keycloak
installkeycloak: false

autoconfigureagent: false
