spring:
  datasource:
{{- if (eq .Values.secretStore "db") }}
    url: {{ .Values.db.url }}/oesdb
    username: '{{ .Values.db.username }}'
    password: '{{ .Values.db.password }}'
{{- end }}

message-broker:
  enabled: true
  username: '{{ .Values.rabbitmq.username }}'
  password: '{{ .Values.rabbitmq.password }}'
  host: rabbitmq-service
  port: {{ .Values.rabbitmq.port }}
  endpoint:
    name: rabbitmq

standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv

argo:
  manifest:
    newArgoAgentTemplate: newargoagentmanifest.template
    newArgoAgentWithoutUrlTemplate: newargoagentmanifestwithouturl.template
    existingArgoAgentTemplate: existingargoagentmanifest.template
    existingArgoAgentWithoutUrlTemplate: existingargoagentmanifestwithouturl.template
    newArgoAgentWithoutRolloutsTemplate: newargoagentwithoutrollouts.template
    newArgoAgentWithoutRolloutsWithoutUrlTemplate: newargoagentwithoutrolloutswithouturl.template

controller:
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
secretManagement:
  source:
    config: {{ .Values.secretStore }}
  encryption: true
oes:
  rbac:
    enabled: true
  admin:
    user: admin
  platform:
    url: http://oes-platform:8095
  visibility:
    url: http://oes-visibility:8096
  auditservice:
    enabled: true
    url: "http://oes-audit-service:8097"
  dashboard:
    url: http://oes-dashboard:8094
  commongateurl: {{ .Values.global.oesUI.protocol }}://{{ .Values.global.oesUI.host }}/gate
spinnaker:
  encrypt:
    enabled: {{ .Values.sapor.config.encrypt.enabled }}
  sync:
    permission:
      enabled: {{ .Values.sapor.config.sync.permission.enabled }}

datasources:
  platform: {{ .Values.sapor.config.datasources.platform }}

pipeline-promotion:
  github:

    enabled: true

    username:  git/stash_username
    token: git/stash_token
    branch: master
    cloneUrl: https://git/stash_username:git/stash_token@github.com/OpsMx/standard-gitops-repo
  bitbucket:

    enabled: false

    username:  git/stash_username
    token: git/stash_token
    branch: master
    cloneUrl: https://git/stash_username:git/stash_token@github.com/OpsMx//standard-gitops-repo
  amazonS3:

    enabled: false

    accessKeyId: AWS_ACCESS_KEY_ID
    secretAccessKey: AWS_SECRET_ACCESS_KEY
    region: regionofbucket
    bucketName: bucket name.e.g-testbucket

## Set the below field to true if agent for kubernetes
kubernetes:
  kinds:
  omitKinds:
  - podPreset
  agent:
    enabled: {{ .Values.forwarder.enabled }}
    serverInternalHostName: opsmx-controller-controller1
    serverPort: 9003
    caCertfile: /opt/opsmx/controller/ca.crt
    certFile: /opt/opsmx/controller/cert/tls.crt
    keyFile: /opt/opsmx/controller/cert/tls.key
    image: {{ .Values.forwarder.agent.image }}
  template:
    path: /opt/opsmx/controller
    kubectlTemplateFileName: kubeconfig.template
    manifestTemplateFileName: deploy-agent.template

