{{- if eq .Values.installationMode "OEA-AP" -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: rabbitmq
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.rabbitmq.serviceAnnotations }}
  annotations:
{{ toYaml .Values.rabbitmq.serviceAnnotations | indent 4 }}
{{- end }}
  name: rabbitmq-service
spec:
  ports:
  - name: rabbitmq
    port: 5672
    protocol: TCP
    targetPort: 5672
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 5672
    {{- end }}
  - name: rabbitmq-mgmt
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: oes
    component: rabbitmq
  type: {{ .Values.k8sServiceType }}
{{- end -}}
