{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: autopilot
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.autopilot.serviceAnnotations }}
  annotations:
{{ toYaml .Values.autopilot.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-autopilot
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: "cas-service"
    port: 8090
    targetPort: 8090
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 8090
    {{- end }}
  - name: "monitoring-service"
    port: 9090
    targetPort: 9090
  selector:
    app: oes
    component: autopilot
{{- end -}}
