{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: datascience
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.datascience.serviceAnnotations }}
  annotations:
{{ toYaml .Values.datascience.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-datascience
spec:
  ports:
  - name: datascience
    port: 5005
    protocol: TCP
    targetPort: 5005
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 5005
    {{- end }}
  selector:
    app: oes
    component: datascience
  type: {{ .Values.k8sServiceType }}
{{- end -}}
