{{- if and (.Values.global.createIngress) (.Values.installArgoCD) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.global.certManager.installed }}
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Release.Namespace }}-argocd
{{- end }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
{{- if .Values.global.ssl.enabled }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
{{- else }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
{{- end }}
{{- if .Values.global.argocd.ingress.annotations }}
{{ tpl (toYaml .Values.global.argocd.ingress.annotations) . | indent 4 }}
{{- end }}
  name: argocd-ingress
spec:
  rules:
  - host: {{ .Values.global.argocd.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-argocd-server
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
{{- if .Values.global.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.global.argocd.host }}
{{ toYaml .Values.global.argocd.ingress.tls | indent 4 }}
{{- end }}
{{- end -}}
