{{- if and (.Values.global.createIngress) (.Values.installArgoRollouts) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.global.certManager.installed }}
    cert-manager.io/cluster-issuer: letsencrypt-{{ .Release.Namespace }}-argocd
{{- end }}
{{- if .Values.global.argorollouts.ingress.annotations }}
{{ tpl (toYaml .Values.global.argorollouts.ingress.annotations) . | indent 4 }}
{{- end }}
  name: argo-rollouts-ingress
spec:
  rules:
  - host: {{ .Values.global.argorollouts.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-argo-rollouts-dashboard
            port:
              number: 3100
        path: /
        pathType: ImplementationSpecific
{{- if .Values.global.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.global.argorollouts.host }}
{{ toYaml .Values.global.argorollouts.ingress.tls | indent 4 }}
{{- end }}
{{- end -}}
