{{- if .Values.global.createIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-{{ .Release.Namespace }}-oes
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: controller-ingress
spec:
  rules:
  - host: {{ .Values.forwarder.agent.host }}
    http:
      paths:
      - backend:
          service:
            name: agent-grpc
            port:
              number: 9001
        path: /
        pathType: ImplementationSpecific
{{- if .Values.global.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.forwarder.agent.host }}
{{ toYaml .Values.forwarder.agent.ingress.tls | indent 4 }}
{{- end }}
{{- end }}