{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: auditservice
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.audit.serviceAnnotations }}
  annotations:
{{ toYaml .Values.audit.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-audit-service
spec:
  ports:
  - name: auditservice
    port: 8097
    protocol: TCP
    targetPort: 8097
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 8097
    {{- end }}
  selector:
    app: oes
    component: auditservice
  type: {{ .Values.k8sServiceType }}
{{- end -}}
