{{- if or (eq .Values.installationMode "OEA-AP") (eq .Values.installationMode "None") }}
{{- if or (.Values.installArgoRollouts) (.Values.installArgoCD) }}
apiVersion: v1
kind: Secret
metadata:
  name: opsmx-profile
stringData:
  {{- if .Values.installArgoCD }}
  cdIntegration: "true"
  {{- else }}
  cdIntegration: "false"
  {{- end }}
  sourceName: {{ .Values.cdagentname | quote }}
  {{- if .Values.global.createIngress }}
  opsmxIsdUrl: "{{ .Values.global.oesUI.protocol }}://{{ .Values.global.oesUI.host }}"
  {{- else }}
  opsmxIsdUrl: http://oes-gate:8084
  {{- end }}
  user: "admin"
{{- end }}
{{- end }}
