{{- if .Values.global.secretmanagement.vault }}
apiVersion: v1
stringData:
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: {{ .Values.global.secretmanagement.roleid }}
  AVP_SECRET_ID: {{ .Values.global.secretmanagement.secretid }}
  AVP_TYPE: vault
  VAULT_ADDR: {{ .Values.global.secretmanagement.vaultaddress}}
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
type: Opaque
{{- end }}
