{{- if and (.Values.installArgoCD) (.Values.autoconfigurecarina) }}
argos:
  - name: oesargo
    {{- if and (.Values.global.createIngress) (.Values.global.certManager.installed) }}
    url: https://{{ .Values.global.argocd.host }}
    {{- else }}
    {{- if and (.Values.global.createIngress) (not .Values.global.certManager.installed) }}
    url: http://{{ .Values.global.argocd.host }}
    {{- else }}
    url: http://{{ .Release.Name }}-argocd-server:80
    {{- end }}
    {{- end }}
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
{{- end }}
httpListenPort: 8091
rbac:
  httpListenPort: 8092
controller:
  url: 'https://opsmx-controller-controller1:9003'
  caPath: /app/secrets/controller-ca.crt
  certificatePath: /app/secrets/controller-control/tls.crt
  keyPath: /app/secrets/controller-control/tls.key
  updateFrequencySeconds: 30
databases:
  audit:
    type: postgresql
    connectString: host=oes-db  user='{{ .Values.db.username }}' password='{{ .Values.db.password }}' database=auditdb
  platform:
    type: postgresql
    connectString: host=oes-db user='{{ .Values.db.username }}' password='{{ .Values.db.password }}' database=platformdb
