{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
stringData:
  visibility-local.yml: |
    {{- tpl (.Files.Get "config/oes-visibility/visibility-local.yml") . | nindent 4 }}
kind: Secret
metadata:
  name: oes-visibility-config
  labels:
    app: oes
    component: visibility
{{ include "oes.standard-labels" . | indent 4 }}
{{- end -}}
