{{- if or .Values.installkeycloak .Values.autoconfigureagent }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oes-auto-configure-{{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oes-auto-configure-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: oes-auto-configure-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- else }}
{{- if (eq .Values.installationMode "OEA-AP") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: isd-auto-configure-{{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: isd-auto-configure-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: isd-auto-configure-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
