{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: sapor
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.sapor.serviceAnnotations }}
  annotations:
{{ toYaml .Values.sapor.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-sapor
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: "sapor"
    port: 8085
    targetPort: 8085
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 8085
    {{- end }}
  selector:
    app: oes
    component: sapor
{{- end -}}
