###########################################################
# Sample agent-services configuration file
# The following need to be changed in the "outgoingServices" before applying
# 1. name: Change to reflect your agent name
# 2. config.url: Point the argo-cd URL. If it is httpS-URL, then "insecure" must be set to "false"
# 3. config.credentials.token: This is a base64 encoded token that can be obtained as follows:
#     argocd login --sso <external host name> #e.g cd.ryzon7-argo22.opsmx.org
#     argocd account generate-token
#     echo -ne "<TOKEN>" | base64 -w0 
# 4. config.credentials.uiUrl: this is the external argoCD URL e.g https://cd-agent.ryzon7-argo22.opsmx.org
###########################################################
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    agent.opsmx.com/name: CHANGE-ME # argodev
    agent.opsmx.com/role: agent
  name: opsmx-services-linode1
  namespace: default
data:
  services.yaml: |
    outgoingServices:
      - name: CHANGE-ME # argodev
        type: argocd
        enabled: true
        config:
          url: http://AGENT-ARGOCD-SERVER:80  # Change this service URL or external URL
          insecure: true # CHANGE this false if url starts with "https://"
          credentials:
            type: bearer
            token: FOLLOW-INSTRUCTIONS-ABOVE
            #secretName: SECRET-CONTAINING-TOKEN #alternative to putting the token, Not tested
          annotations:
            description: argocd via agent
            uiUrl: https://EXTERNAL-URL-OF-ARGOCD.OPSMX.ORG
