{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
{{ include "oes.standard-labels" . | indent 4 }}
spec:
  selector:
    app: opa
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 8181
    {{- end }}
  type: {{ .Values.k8sServiceType }}
{{- end -}}
