{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: platform
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.platform.serviceAnnotations }}
  annotations:
{{ toYaml .Values.platform.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-platform
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: oes-platform
    protocol: TCP
    port: 8095
    targetPort: 8095
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 8095
    {{- end }}
  selector:
    app: oes
    component: platform
{{- end -}}
