{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.ui.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ui.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-ui
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: "https"
    port: 443
    targetPort: 8093
  - name: "http"
    port: 8093
    targetPort: 8093
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: 8093
    {{- end }}
  selector:
    app: oes
    component: ui
{{- end -}}
