{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
data:
{{ (tpl (.Files.Glob "config/oes-ui/nginx-ap-only.conf").AsConfig . ) | indent 2 }}
kind: ConfigMap
metadata:
  name: oes-ui-nginxconf
  labels:
    app: oes
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
{{- end -}}
