{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: carina
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-carina
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: carina
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oes
        component: carina
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
        checksum/secret: {{ (.Files.Glob "config/carina/carina-manager.yaml").AsConfig | sha256sum }}
{{- if .Values.carinamanager.annotations -}}
        {{ toYaml .Values.carinamanager.annotations | nindent 8 }}
{{- end }}
    spec:
      initContainers:
      - name: platform-check
        image: {{ .Values.global.customImages.registry }}/pgchecker:v1
        command:
          - sh
          - -c
          - |
            echo 'Waiting for OES-PLATFORM to become ready...'
            until printf "." && nc -z -w 2 oes-platform 8095; do
               sleep 2;
            done;
            echo 'OES PLATFORM is OK ✓'
      containers:
      - image: {{ template "carinamanager.image" . }}
        imagePullPolicy: IfNotPresent
        name: oes-carina
        ports:
        - containerPort: 8090
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/secrets/controller-ca.crt
          name: ca-certs-volume
          subPath: tls.crt
        - mountPath: /app/secrets/controller-control/tls.crt
          name: certs-volume
          subPath: tls.crt
        - mountPath: /app/secrets/controller-control/tls.key
          name: certs-volume
          subPath: tls.key
        - mountPath: /app/config/carina-manager.yaml
          name: carina-volume
          subPath: carina-manager.yaml
      dnsPolicy: ClusterFirst
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs-volume
        secret:
          defaultMode: 420
          secretName: oes-control-secret
      - name: ca-certs-volume
        secret:
          defaultMode: 420
          secretName: ca-secret
      - secret:
          items:
          - key: carina-manager.yaml
            path: carina-manager.yaml
          secretName: oes-carina-config
        name: carina-volume
{{- end -}}
