{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
stringData:
  carina-manager.yaml: |
    {{- tpl (.Files.Get "config/carina/carina-manager.yaml") . | indent 4 }}
kind: Secret
metadata:
  labels:
    app: oes
    component: carina
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-carina-config
{{- end -}}
